name: Test Flask Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirement.txt

      - name: Start Flask Server
        run: |
          nohup python Serveur_API.py &  # Lance en arrière-plan
          sleep 5  # Attends que le serveur démarre

      - name: Test Flask Server
        run: curl --fail http://127.0.0.1:5000 || exit 1  # Vérifie si le serveur répond

      - name: Stop Flask Server
        run: pkill -f Serveur_API.py  # Termine le processus Flask
